export const Ar = {
  Username: "اسم المستخدم",
  Password: "كلمه السر",
  SignIn: "تسجيل دخول",
  SelectSite: "أختر موقع",
  Proceed: "متابعه",
  Home: "الرئيسيه",
  PlaceOrder: "طلب صرف",
  ScanItem: "مسح الصنف",
  Menu: "القائمه",
  SignOut: "تسجيل خروج",
  SelectProcessName: "أختر نوع العمليه",
  New: "صنف جديد",
  Transition: "تحويل",
  Recieve: "وارد محول من عمليه",
  Exchange: "صرف",
  NewDesc:
    "صنف يدخل المخزن من جهه من هؤلاء (مشتريات, فاتوره من المانيا, مرتجع أو من مورد )",
  TransitionDesc: "صنف موجه لمخزن اخر",
  RecieveDesc: "صنف مستلم من مخزن اخر",
  ExchangeDesc: "أى صنف سيصرف علي معده أو ورشه",
  SelectCategory: "اختر الفئه",
  Invoice: "فاتوره",
  ReturnItem: "مرتجع",
  Procurment: "مشتريات",
  Vendors: "مورد",
  InvoiceDesc: "الاصناف القادمه بفاتوره من المانيا",
  ReturnItemDesc: "الاصناف المرتجعه من الفنيين",
  ProcurmentDesc: "الاصناف القادمه بواسطه قسم المشتريات بالاداره",
  VendorsDesc: "الاصناف القادمه مباشره من المورد",
  SelectInvoce: "اختر رقم الفاتوره",
  SelectProcurmentNo: "اختر رقم اوردر الشراء",
  TapToScanAgain: "مسح مره اخري",
  Scan: "مسح",
  Confirm: "تأكيد",
  Confirmed: "تم التأكيد",
  Pending: "قيد الانتظار",
  SearchForItems: "بحث عن صنف",
  OrderNo: "رقم الاوردر",
  TypeItemCode: "كود الصنف",
  Quantity: "الكميه",
  Save: "حفظ",
  Saved: "تم الحفظ",
  Finish: "انهاء",
  Finished: "تم الانتهاء",
  Send: "ارسال",
  Sent: "تم الارسال",
  Add: "اضافه",
  Delete: "مسح",
  Code: "كود الصنف",
  SabCode: "كود الساب",
  Unit: "الوحده",
  Store: "المخزن",
  Description: "توصيف",
  Position: "مكان الصنف في المخزن",
  Details: "تفاصيل عن الصنف",
  Submit: "تأكيد",
  SelectStoreTo: "اختر المخزن المحول اليه",
  SelectStoreFrom: "اختر المخزن المحول منه",
  SelectEquipment: "اختر المعده",
  SuccessfullySparepartRecieved: "تم استلام الصنف بنجاح",
  Successfullylogin: "تم تسجيل الدخول بنجاح",
  SuccessfullySparepartLeft: "نم خروج الصنف بنجاح",
  SuccessfullySparepartConsumed: "تم صرف الصنف بنجاح",
  SuccessfullySparepartAdded: "تم اضافه الصنف بنجاح",
  SuccessfullyOrderConfirmed: "نم تأكيد الاوردر بنجاح",
  MustSaveAllItems: "يجب حفظ كل البنود",
  Details: "تفاصيل",
  SuccessfullyPlacedOrder: "تم عمل طلب الصرف بنجاح",
  Pending: "الاصناف المنتظره",
  Transitions: "تحركات الاصناف",
  Consumptions: "استهلاكات الاصناف",
  Analysis: "تحليل",
  AddItemsInStock: "اضافه صنف بكود مخزن جديد",
  Equipment: "معده",
  EquipmentDesc: "صنف يصرف علي معده",
  WorkShop: "ورشه",
  WorkShopDesc: "صنف يصرف علي ورشه",
  AddWorkshopName: "اضافه اسم الورشه",
  WorkshopName: "اسم الورشه",
  SelectWorkshop: "اختر ورشه",
  ActualQuantity: "الكميه الحاليه",
};

export const En = {
  Username: "Username",
  Password: "Password",
  SignIn: "Sign In",
  SelectSite: "Select Site",
  Proceed: "Proceed",
  Home: "Home",
  PlaceOrder: "Place Order",
  ScanItem: "Scan Item",
  Menu: "Menu",
  SignOut: "Sign Out",
  SelectProcessName: "Select Process Name",
  New: "New",
  Transition: "Transition",
  Recieve: "Recieve",
  Exchange: "Exchange",
  NewDesc:
    "New item comming from on of this sources (Procurment , Invoice, Return Item Or Vendor)",
  TransitionDesc: "Item Consume By Another Store",
  RecieveDesc: "Item Recieved From Another Store",
  ExchangeDesc: "Item Consume By an Equipment",
  SelectCategory: "Select Category",
  Invoice: "Bauer Eq. Invoice",
  ReturnItem: "Return Item",
  Procurment: "Procurment",
  Vendors: "Vendors",
  InvoiceDesc: "Invoices Coming From Germany",
  ReturnItemDesc: "Items Returns From Technicians",
  ProcurmentDesc: "Items Coming From Egypt Procurment Department",
  VendorsDesc: "Items Coming Directly From Vendors",
  SelectInvoce: "Select Invoice No",
  SelectProcurmentNo: "Select Procurment No",
  TapToScanAgain: "Tap to Sacn Again",
  Scan: "Scan",
  Confirm: "Confirm",
  Confirmed: "Confirmed",
  Pending: "Pending",
  SearchForItems: "Search For Item",
  OrderNo: "Order No",
  TypeItemCode: "Type Item Code",
  Quantity: "Quantity",
  Save: "Save",
  Saved: "Saved",
  Finish: "Finish",
  Finished: "Finished",
  Send: "Send",
  Sent: "Sent",
  Add: "Add",
  Delete: "Delete",
  Code: "Code",
  SabCode: "Sab Code",
  Unit: "Unit",
  Store: "Store",
  Description: "Description",
  Position: "Position",
  Details: "Details",
  Submit: "Submit",
  SelectStoreTo: "Select To Store",
  SelectStoreFrom: "ٍSelect From Store",
  SelectEquipment: "Select Equipment",
  SuccessfullySparepartRecieved: "Successfully Spare part Recieved",
  Successfullylogin: "Successfully login",
  SuccessfullySparepartLeft: "Successfully Spare part Left",
  SuccessfullySparepartConsumed: "Successfully Spare part Consumed",
  SuccessfullySparepartAdded: "Successfully Spare part Added",
  SuccessfullyOrderConfirmed: "Successfully Order Confirmed",
  MustSaveAllItems: "Must Save All Items",
  Details: "Details",
  SuccessfullyPlacedOrder: "Successfully Placed Order",
  Pending: "Pending",
  Transitions: "Transitions",
  Consumptions: "Consumptions",
  Analysis: "Analysis",
  AddItemsInStock: "Add Items With New Stock Code",
  Equipment: "Equipment",
  EquipmentDesc: "Item Consume by Equipment",
  WorkShop: "WorkShop",
  WorkShopDesc: "Item Consume by Workshops",
  AddWorkshopName: "Add Workshop Name",
  WorkshopName: "Workshop Name",
  SelectWorkshop: "Select Workshop",
  ActualQuantity: "Current Quantity",
};
